In [1]:
print('Hello World')

Hello World

In [1]:
l=[]
e=[]
o=[]
a=int(input('Enter a value'))
for i in range(a):
    b=int(input('Enter the list element'))
    l.append(b)
print(l)

k=0
for i in range(a):
    if (l[k]%2==0):
        e.append(l[k])
    
    else:
        o.append(l[k])
        
    l.remove(l[k])
    
print('The list =',l)
print('Even list =',e)
print('Odd list =',o)

Enter a value5
Enter the list element1
Enter the list element2
Enter the list element3
Enter the list element4
Enter the list element5
[1, 2, 3, 4, 5]
The list = []
Even list = [2, 4]
Odd list = [1, 3, 5]

# l=(Tuple input)
e=()
o=()
a=int(input('Enter the no. of values to be inserted in list :'))
for i in range(a):
    b=int(input('Enter the list element :'))
    l=list(l)
    l.append(b)
    
print(l)

k=0
for i in range(a):
    if (l[k]%2==0):
        e=list(e)
        e.append(l[k])
        e=tuple(e)
    
    else:
        o=list(o)
        o.append(l[k])
        o=tuple(o)
        
    l.remove(l[k])
l=tuple(l)
    
print('The list =',l)
print('Even list =',e)
print('Odd list =',o)

In [18]:
a=int(input("Input a no."))
i=0
if a>0:
     while i<a:
            print('Vedant')
            i+=1

Input a no.4
Vedant
Vedant
Vedant
Vedant

In [2]:
a=int(input('Input a no. '))
if a>0:
    i=1
    while i<=a:
        print(a+i)
        i+=1

Input a no. 3
4
5
6

In [5]:
a=int(input('Input a no. '))
b=2*a
if a>0:
    while b>a:
        a+=1
        print(a)

Input a no. 4
5
6
7
8

In [ ]:
A=0                           #fan
B=0                            #Tv
C=0                            #Light
i=0
x=input("Input char from A,B,C:")

while i<5:
    i+=1
    if x==A:
        if A==0:
            A+=1
        else:
            A-=1

    elif x==B:
        if B==0:
            B+=1
        else:
            B-=1

    elif x==C:
        if C==0:
            C+=1
        else:
            C-=1
#if x==Y:
      #  continue

  #  elif x==N:
  #  break

    else:
        print("Invalid input")
        continue
    

print('The reaction of your condition is : A='+str(A)+ "B="+str(B)+"C="+str(C))
print('Do you wish to continue=Y/N :')

In [5]:
a=0                            
b=0                            
c=0 
y=1
while True:
        x=input("\nInput Option from A,B,C or E for exit :")

        if x=="A" or x=="a":
            if a==0:
                a+=1
            else:
                a-=1l 

        elif x=="B" or x=="b":
            if b==0:
                b+=1
            else:  
                b-=1

        elif x=="C" or x=="c":
            if c==0:
                c+=1
            else:
                c-=1
                
        elif x=="E" or "e":
            break

        else:
            print("Invalid input")

        print('{}{}{}'.format(a,b,c))

Input Option from A,B,C or E for exit :a
100

Input Option from A,B,C or E for exit :b
110

Input Option from A,B,C or E for exit :c
111

Input Option from A,B,C or E for exit :a
011

Input Option from A,B,C or E for exit :b
001

Input Option from A,B,C or E for exit :c
000

Input Option from A,B,C or E for exit :e

In [20]:
a=(1000.split())
for i in a:
    if i==(i**3):
        print('The {} is an armstrong no.'.format(i))
            
   # else:
       # print('The {} is not an armstrong no.'.format(i))
#else:
   # print('Invalid value=>Enter value in the range of 1 to 10')

SyntaxError: invalid syntax (<ipython-input-20-d7441a16a803>, line 1)

In [22]:
a=input('String'.split())
for i in a:
    print(i[0])

['String']2000
2
0
0
0

In [21]:
a=1000
print(a[0])

TypeError: 'int' object is not subscriptable

# Armstrong Number
b=len(a)
a=int(a)
t=a
s=0
while(t>0):
    d=t%10
    s=s+(d**b)
    t=t//10
    
if(a==s):
    print("Entered no. {} is a armstrong no.".format(a))
    
else:
    print("Entered no {} is not a armstrong no.".format(a))

In [1]:
import pandas

# Armstrong Number

In [7]:
a=input("Input a number :")
b=len(a) 
a=int(a) 
t=a 
s=0 
while(t>0): 
    d=t%10 
    s=s+(d**b) 
    t=t//10
    print(d,t)

if(a==s): 
    print("Entered no. {} is a armstrong no.".format(a))

else: 
    print("Entered no {} is not a armstrong no.".format(a))

Input a number :1634
4 163
3 16
6 1
1 0
Entered no. 1634 is a armstrong no.

In [8]:
import pandas as Pd
l=[['Vedant',40],['hrishi',25]]
df=Pd.DataFrame(l,columns=['Names','Age'])
print(df)

    Names  Age
0  Vedant   40
1  hrishi   25

# For adding columns in above table

In [4]:
import pandas as Pd
l=[['Vedant',40],['hrishi',25]]
df=Pd.DataFrame(l,columns=['Names','Age'],index=['1st','2nd'])
df['Date']=['2019-10-15','2019-10-15']
df['Time']=['09:20','09:20']

print(df)

      Names  Age        Date   Time
1st  Vedant   40  2019-10-15  09:20
2nd  hrishi   25  2019-10-15  09:20

For merging two columns

In [7]:
import pandas as Pd
l=[['Vedant',40],['hrishi',25]]
df=Pd.DataFrame(l,columns=['Names','Age'],index=['1st','2nd'])
df['Date']=['2019-10-15','2019-10-15']
df['Time']=['09:20','09:20']
df['Merge']=df['Date'] + df['Time']
print(df)

1st    09:20
2nd    09:20
Name: Time, dtype: object

For deleting column

In [9]:
import pandas as Pd
l=[['Vedant',40],['hrishi',25]]
df=Pd.DataFrame(l,columns=['Names','Age'],index=['1st','2nd'])
df['Date']=['2019-10-15','2019-10-15']
df['Time']=['09:20','09:20']
df['Merge']=df['Date'] + df['Time']
del df['Date']
del df['Time']
print(df)

      Names  Age            Merge
1st  Vedant   40  2019-10-1509:20
2nd  hrishi   25  2019-10-1509:20

In [6]:
print(df)

   Name  Age
0   ved  4.0
1  hris  5.0

Adding nonsymmetric data

In [14]:
import pandas as Pd
l=[{'a':1,'b':2,'c':3},{'a':4,'b':5}]
df=Pd.DataFrame(l)
print(df)

   a  b    c
0  1  2  3.0
1  4  5  NaN

In [2]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\vedant\anaconda3\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as Pd
df=Pd.read_excel('C:/Users/VEDANT/Desktop/Pythondemo.xlsx')
print(df)

     Vehicle No.   Name  Mobile      Address
0  KA-04-Fy-3320  Vansi   34556  Rajajinagar
1  KA-04-Fy-3321    Sid   34556    Jalahalli
2  KA-04-Fy-3322    Adi    3455   Dasarhalli
3  KA-04-Fy-3323    Ved   23677  Rajajinagar
4  KA-04-Fy-3324   Sand   56585   Dasarhalli

In [1]:
import pandas as Pd
df=Pd.read_excel('C:/Users/VEDANT/Desktop/Pythondemo.xlsx')
print(df['Name'])

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/VEDANT/Desktop/Pythondemo.xlsx'

In [ ]:
import pandas as Pd
df=Pd.read_excel('C:/Users/VEDANT/Desktop/Pythondemo.xlsx')
print(df)

x=list(df['Name'])
a=list(df['Vehicle No.'])
b=list(df['Mobile'])
c=list(df['Address'])

m=len(x)

j=range(m)
k=range(m)
p=range(m)

while True:
    y=input("Enter Name to be searched :")
    for i in range(m):
        if x[i]==y:
            j=k=p=i
            print("\nThe details for following name {} are : \nVehicle no.: {}\nMobile: {}\nAddress: {}".format(x[i],a[j],b[k],c[p]))
            break
            
    else:
        print("Given Name {} is not present".format(y))

     Vehicle No.   Name  Mobile      Address
0  KA-04-Fy-3320  Vansi   34556  Rajajinagar
1  KA-04-Fy-3321    Sid   34556    Jalahalli
2  KA-04-Fy-3322    Adi    3455   Dasarhalli
3  KA-04-Fy-3323    Ved   23677  Rajajinagar
4  KA-04-Fy-3324   Sand   56585   Dasarhalli
Enter Name to be searched :Sand

The details for following name Sand are :
Vehicle no.: KA-04-Fy-3324
Mobile: 56585
Address: Dasarhalli
Enter Name to be searched :saa
Given Name saa is not present
Enter Name to be searched :Ved

The details for following name Ved are :
Vehicle no.: KA-04-Fy-3323
Mobile: 23677
Address: Rajajinagar

In [2]:
import pandas as Pd
df=Pd.read_excel('C:/Users/VEDANT/Desktop/Pythondemo.xlsx')
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/VEDANT/Desktop/Pythondemo.xlsx'

loc function used for location

In [12]:
import pandas as Pd 
df=Pd.read_excel('C:/Users/VEDANT/Desktop/Pythondemo.xlsx')
print(df)
vnl=list(df['Vehicle No.'])
a=input('Vehicle No. :')

p=vnl.count(a)            #count()=check if element inside bracket is present or not and will provide the count for how mny.
print(p)
if(p>0):
    pos=vnl.index(a)
    #print(pos)
    print(df.loc[pos])
else:
    print('Vehicle no. not in list')

     Vehicle No.   Name  Mobile      Address
0  KA-04-Fy-3320  Vansi   34556  Rajajinagar
1  KA-04-Fy-3321    Sid   34556    Jalahalli
2  KA-04-Fy-3322    Adi    3455   Dasarhalli
3  KA-04-Fy-3323    Ved   23677  Rajajinagar
4  KA-04-Fy-3324   Sand   56585   Dasarhalli
Vehicle No. :KA-04-Fy-3323
1
Vehicle No.    KA-04-Fy-3323
Name                     Ved
Mobile                 23677
Address          Rajajinagar
Name: 3, dtype: object

In [3]:
import pandas as Pd
l=[['ved',4],['hris',5]]
df=Pd.DataFrame(l,columns=['Name','Age'],dtype=float)
print(df)

   Name  Age
0   ved  4.0
1  hris  5.0

In [5]:
print(df)

   Name  Age
0   ved  4.0
1  hris  5.0

# mySQL

In [2]:
pip install mysql-connector

Requirement already satisfied: mysql-connector in c:\users\vedant\anaconda3\lib\site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import mysql.connector as msc
ser=msc.connect(host='localhost',user='root',passwd='root')
print(ser)

<mysql.connector.connection.MySQLConnection object at 0x0000024BD5BE00F0>

In [4]:
import mysql.connector as msc
ser=msc.connect(host='localhost',user='root',passwd='root',database='Ved')
a=ser.cursor()
a.execute('CREATE DATABASE Ved')
a.execute('CREATE TABLE student(Name varchar[10],Mobile int[10],Mailid varchar[20])')

DatabaseError: 1007 (HY000): Can't create database 'ved'; database exists

In [8]:
import mysql.connector as msc
ser=msc.connect(host='localhost',user='root',passwd='root',database='Ved')
a=ser.cursor()
a.execute('CREATE TABLE student(Name varchar[10],Mobile int[10],Mailid varchar[20])')

ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[10],Mobile int[10],Mailid varchar[20])' at line 1

In [10]:
import mysql.connector as msc
ser=msc.connect(host='localhost',user='root',passwd='root',database='Student')
a=ser.cursor()
print(ser)
#a.execute('CREATE DATABASE Student')
a.execute('CREATE TABLE student(Name varchar(10),Mobile int(10),Mailid varchar(20))')

<mysql.connector.connection.MySQLConnection object at 0x000001C9323A7A20>

In [10]:
a.execute('CREATE TABLE student(Name varchar[10],Mobile int[10],Mailid varchar[20])')

ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[10],Mobile int[10],Mailid varchar[20])' at line 1

In [1]:
def hi():
    print("hi")
    hi()
hi()

hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi

RecursionError: maximum recursion depth exceeded while calling a Python object

In [3]:
print("edu\\onl\\tr.txt")

edu\onl\tr.txt

In [11]:
import pandas as pd
df=pd.read_excel('C:/Users/VEDANT/Desktop/Python softwares/Country.xlsx')
print(df)
A=list(df['COUNTRY'])
B=list(df['AREA'])
C=list(df['POPULATION'])
try:
    a=input('Country name :')
   # b=input('Area=X/Population=Y :')
    pos=A.index(a)
    print(pos)
    pos1=B.index(pos)
    print(df.loc[pos1])
except:
    print('Country name is not in the list')

       COUNTRY     CAPITAL  AREA  POPULATION
0        India       Delhi   500           1
1          USA  Washington   400          23
2      Germany      Berlin   700           3
3       Africa   Cape Town   500           4
4        China    Beinjing   200           5
5        Japan       Tokyo    50           6
6  Switzerland        Bern  4667           7
7          UAE   Abu dhabi    98           5
8           UK      London   543           3
9        Spain      Madrid   235          45
Country name :India
0
Country name is not in the list

In [4]:
s="'Hi Iam Vedant Iam python dev Python is very interesting concept Python doesnt have syntax i will suggest python to evryone'"
d=s.split()
l=[]
d1={}
s=set(d)
s=list(s)
j=0
for i in s:
    l.append(d.count(i))
    d1[i]=s[j]
    j+=1
print(l)

[1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1]

In [5]:
j=0
n=4
for i in range(1,6):
    print("_"*n,i,"_"*j)
    n-=1
    j+=1

____ 1
___ 2 _
__ 3 __
_ 4 ___
 5 ____

In [13]:

def reverse(s): 
    str = "" 
    for i in s: 
        str = i + str
        if i==str:
            print('P')
        else:
            print('N')
    return str
s='MADAn'
print(reverse(s))

P
N
N
N
N
nADAM

# Time module

In [1]:
import time
a=time.ctime()
print(a)
time.sleep(60)
a=time.ctime()
print(a)

Wed Oct 23 09:42:52 2019
Wed Oct 23 09:43:52 2019

Creating a file

In [3]:
a=int(input("Enter no. of files to be created :"))
for i in range(a): 
    f=open(str(i)+".doc",'w')
    f.close()

Enter no. of files to be created :4

In [20]:
a=open('C:/Users/VEDANT/python/CODES/File/Karthik.txt','w')
#a.write('Vedant')
a.close()
b=open('C:/Users/VEDANT/python/CODES/File/Archana.txt','w')
#b.write('Shlok')
b.close()
c=open('C:/Users/VEDANT/python/CODES/File/Sandeep.txt','w')
c.write('Sidhu')
c.close()

In [30]:
inp = input("Enter file name : ")
r = open('C:/Users/VEDANT/python/CODES/File/'+ str(inp) +'.txt','r')
a = r.read()
print(a)
r.close()
if inp == 'Sandeep':
    r1 = open('Karthik.txt','r')
    b = r1.read()
    w = open('Archana.txt','w')
    w.write(a)
    w.write(b)
    w.close()
    r1.close()
    r2 = open('Archana.txt','r')
    c = r2.read()
    print(c)
elif inp == 'Karthik':
    r1 = open('Sandeep.txt','r')
    b = r1.read()
    w = open('Archana.txt','w')
    w.write(a)
    w.write(b)
    w.close()
    r1.close()
    r2 = open('Archana.txt','r')
    c = r2.read()
    print(c)
elif inp == 'Archana':
    r1 = open('Karthik.txt','r')
    b = r1.read()
    w = open('Sandeep.txt','w')
    w.write(a)
    w.write(b)
    w.close()
    r1.close()
    r2 = open('Sandeep.txt','r')
    c = r2.read()
    print(c)
else:
    print('Wrong inp')

Enter file name : Sandeep
Sidhu

FileNotFoundError: [Errno 2] No such file or directory: 'Karthik.txt'

In [23]:
a=open('Sandeep.txt','r')
b=a.read()
print(b)
a.close()

FileNotFoundError: [Errno 2] No such file or directory: 'Sandeep.txt'

In [3]:
a=input('Alphabets :')
z=[]
for i in a:
    if ord(i)<=90:
        b=('{}:{}'.format(ord(i),i))
        z()=b
        print(b)
print(z)
inp=input('File name :')
x=open('C:/Users/VEDANT/python/CODES/File/'+ str(inp) +'.txt','w')
x.write(b)
y=open('C:/Users/VEDANT/python/CODES/File/'+ str(inp) +'.txt','r')
r1=y.read()
print(r1)
x.close()
y.close()

SyntaxError: can't assign to function call (<ipython-input-3-4abdcb83d0dc>, line 6)

In [30]:
y=open('C:/Users/VEDANT/python/CODES/File/Archana.txt','r')
r1=y.read()
print(r1)

68:D

OOps assignement

In [12]:
global l,l1,l2
l=[]
l1=[]
l2=[]
class course:
    def Python(self,n):
        l.append(n)
    def ds(self,n):
        l1.append(n)
    def Iot(self,n):
        l2.append(n)

while True:
    vam=course()
    a=input('Enetr the option 1.Reg 2.res')
    if (a=='1'):
        b=input('Enter the name')
        c=input('ENter the course 1.Python 2.Ds 3.Iot')
        if(c=='1'):
            vam.Python(b)
        elif(c=='2'):
            vam.ds(b)
        else:
            vam.Iot(b)
        break     
n=[]
obj=course()
out=obj.Python(n)
print(out)
out1=obj.ds(n)
print(out1)
out2=obj.Iot(n)
print(out2)

Enetr the option 1.Reg 2.res1
Enter the nameddd
ENter the course 1.Python 2.Ds 3.Iot1
None
None
None

In [8]:
class abstract:
    def rec(base,l,b):
        A=l*b
        return A
class base(abstract):
    def rec(base,l,b):
        return A
obj=base()
l=int(input('Enter the length :'))
b=int(input('Enter the base :'))
out=obj.area(l,b)
print('Area of rect=',out)

SyntaxError: invalid syntax (<ipython-input-8-033ba68ff726>, line 1)

# Class overriding

In [13]:
class A:
    def __init__(self):
        self.a=20
        print(a)
    
class B():
    def __init__(self):
        self.a=a+1
        print(a)
obj=A()
obj1=B()
out=obj1.__init__()
print(out)

1

TypeError: can only concatenate str (not "int") to str

In [13]:
class A:
    def some(self):
        print('This is class A')
class B(A):
    pass
obj=B()
obj.some()

This is class A

In [17]:
class A:
    def __init__(self):
        self.a=10
    def data(self):
        print(self.a)
    
class B(A):
    def data(self):
        print(self.a+1)
obj=B()
obj.data()

11

# Fn Overloading

In [ ]:
class A:
    def fun(self,*name):
        if name is not None:
            print('Hi '+name)
        else:
            print('Hi')
            
obj=A()
#a=input('Names :')
obj.fun()
obj.fun('a')
obj.fun('Ved','Shlok')

In [8]:
class A:
    def fun(self,*name):
        if name is not None:
            print('Hi ',name)
        else:
            print('Hi')
            
obj=A()
#a=input('Names :')
#obj.fun()
obj.fun('Ved')
#obj.fun('Ved','Shlok')

Hi  ('Ved',)

# Functions

In [1]:
def add(w,x):
    c=a+b
    return c
def fact(c):
    sum=1
    for i in range(1,c+1):
        sum=i*sum
    return sum
    
a=int(input("ENter a Value :"))
for i in range(3):
    b=int(input("ENter a Value :"))
    c=add(a,b)
    d=fact(c)
    a = d
print(d)

ENter a Value :1
ENter a Value :1
ENter a Value :1
ENter a Value :1
5040

# Recursion fn

In [9]:
def fact(a):
    if a>1:
        return a*fact(a-1)
    else:
        return a
a=int(input("Enter value :"))
fact(a)

Enter value :5

120

# Medicine

In [1]:
import time
a=0
while True:
    inp=input('Did u take medicine :Y/N :')
    if inp=='Y'or inp=='y':
        time.sleep(10)
        print('Have next medicine')
        break
    elif inp=='N'or inp=='n':
        if a==3:    
        break
        time.sleep(3)
        a+=1
        continue

Did u take medicine :Y/N :n
Did u take medicine :Y/N :n
Did u take medicine :Y/N :n
Did u take medicine :Y/N :n

In [34]:
inp=input("ENter Name :")
a=input('"+" or "-" :')
con=len(inp)-1
if a=="+":
    for i in range (1,con+2):
        print(inp[0:i],"*"*con)
        con-=1
elif a=="-":
    b=inp[::-1]
    for i in range (1,con+2):
        print("*"*con,inp[0:i])
        con-=1
else: 
    print("Invalid input")

ENter Name :vedant
"+" or "-" :-
***** v
**** ve
*** ved
** veda
* vedan
 vedant